[project]
name = "classification-informations"
version = "0.1.0"
description = "Project 4 Classification automatique d'informations"
authors = [
    { name = "Ksenia Dautel" }
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.1.0",
    "jupyter>=1.1.1",
    "pandas>=2.3.3",
]
